# coding: utf-8

"""
    OpenBB Platform API

    Investment research for everyone, anywhere.

    The version of the OpenAPI document: 1
    Contact: hello@openbb.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openbb_client.models.te_economic_calendar_data import TEEconomicCalendarData

class TestTEEconomicCalendarData(unittest.TestCase):
    """TEEconomicCalendarData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TEEconomicCalendarData:
        """Test TEEconomicCalendarData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TEEconomicCalendarData`
        """
        model = TEEconomicCalendarData()
        if include_optional:
            return TEEconomicCalendarData(
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                country = '',
                category = '',
                event = '',
                importance = '',
                source = '',
                currency = '',
                unit = '',
                consensus = None,
                previous = None,
                revised = None,
                actual = None,
                forecast = None,
                reference = '',
                reference_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                calendar_id = 56,
                date_span = 56,
                symbol = '',
                ticker = '',
                te_url = '',
                source_url = '',
                last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return TEEconomicCalendarData(
        )
        """

    def testTEEconomicCalendarData(self):
        """Test TEEconomicCalendarData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
