# coding: utf-8

"""
    OpenBB Platform API

    Investment research for everyone, anywhere.

    The version of the OpenAPI document: 1
    Contact: hello@openbb.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openbb_client.api.equity_api import EquityApi


class TestEquityApi(unittest.TestCase):
    """EquityApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EquityApi()

    def tearDown(self) -> None:
        pass

    def test_equity_calendar_dividend(self) -> None:
        """Test case for equity_calendar_dividend

        Dividend
        """
        pass

    def test_equity_calendar_earnings(self) -> None:
        """Test case for equity_calendar_earnings

        Earnings
        """
        pass

    def test_equity_calendar_ipo(self) -> None:
        """Test case for equity_calendar_ipo

        Ipo
        """
        pass

    def test_equity_calendar_splits(self) -> None:
        """Test case for equity_calendar_splits

        Splits
        """
        pass

    def test_equity_compare_company_facts(self) -> None:
        """Test case for equity_compare_company_facts

        Company Facts
        """
        pass

    def test_equity_compare_peers(self) -> None:
        """Test case for equity_compare_peers

        Peers
        """
        pass

    def test_equity_discovery_active(self) -> None:
        """Test case for equity_discovery_active

        Active
        """
        pass

    def test_equity_discovery_aggressive_small_caps(self) -> None:
        """Test case for equity_discovery_aggressive_small_caps

        Aggressive Small Caps
        """
        pass

    def test_equity_discovery_filings(self) -> None:
        """Test case for equity_discovery_filings

        Filings
        """
        pass

    def test_equity_discovery_gainers(self) -> None:
        """Test case for equity_discovery_gainers

        Gainers
        """
        pass

    def test_equity_discovery_growth_tech(self) -> None:
        """Test case for equity_discovery_growth_tech

        Growth Tech
        """
        pass

    def test_equity_discovery_latest_financial_reports(self) -> None:
        """Test case for equity_discovery_latest_financial_reports

        Latest Financial Reports
        """
        pass

    def test_equity_discovery_losers(self) -> None:
        """Test case for equity_discovery_losers

        Losers
        """
        pass

    def test_equity_discovery_undervalued_growth(self) -> None:
        """Test case for equity_discovery_undervalued_growth

        Undervalued Growth
        """
        pass

    def test_equity_discovery_undervalued_large_caps(self) -> None:
        """Test case for equity_discovery_undervalued_large_caps

        Undervalued Large Caps
        """
        pass

    def test_equity_estimates_analyst_search(self) -> None:
        """Test case for equity_estimates_analyst_search

        Analyst Search
        """
        pass

    def test_equity_estimates_consensus(self) -> None:
        """Test case for equity_estimates_consensus

        Consensus
        """
        pass

    def test_equity_estimates_forward_ebitda(self) -> None:
        """Test case for equity_estimates_forward_ebitda

        Forward Ebitda
        """
        pass

    def test_equity_estimates_forward_eps(self) -> None:
        """Test case for equity_estimates_forward_eps

        Forward Eps
        """
        pass

    def test_equity_estimates_forward_pe(self) -> None:
        """Test case for equity_estimates_forward_pe

        Forward Pe
        """
        pass

    def test_equity_estimates_forward_sales(self) -> None:
        """Test case for equity_estimates_forward_sales

        Forward Sales
        """
        pass

    def test_equity_estimates_historical(self) -> None:
        """Test case for equity_estimates_historical

        Historical
        """
        pass

    def test_equity_estimates_price_target(self) -> None:
        """Test case for equity_estimates_price_target

        Price Target
        """
        pass

    def test_equity_fundamental_balance(self) -> None:
        """Test case for equity_fundamental_balance

        Balance
        """
        pass

    def test_equity_fundamental_balance_growth(self) -> None:
        """Test case for equity_fundamental_balance_growth

        Balance Growth
        """
        pass

    def test_equity_fundamental_cash(self) -> None:
        """Test case for equity_fundamental_cash

        Cash
        """
        pass

    def test_equity_fundamental_cash_growth(self) -> None:
        """Test case for equity_fundamental_cash_growth

        Cash Growth
        """
        pass

    def test_equity_fundamental_dividends(self) -> None:
        """Test case for equity_fundamental_dividends

        Dividends
        """
        pass

    def test_equity_fundamental_employee_count(self) -> None:
        """Test case for equity_fundamental_employee_count

        Employee Count
        """
        pass

    def test_equity_fundamental_filings(self) -> None:
        """Test case for equity_fundamental_filings

        Filings
        """
        pass

    def test_equity_fundamental_historical_attributes(self) -> None:
        """Test case for equity_fundamental_historical_attributes

        Historical Attributes
        """
        pass

    def test_equity_fundamental_historical_eps(self) -> None:
        """Test case for equity_fundamental_historical_eps

        Historical Eps
        """
        pass

    def test_equity_fundamental_historical_splits(self) -> None:
        """Test case for equity_fundamental_historical_splits

        Historical Splits
        """
        pass

    def test_equity_fundamental_income(self) -> None:
        """Test case for equity_fundamental_income

        Income
        """
        pass

    def test_equity_fundamental_income_growth(self) -> None:
        """Test case for equity_fundamental_income_growth

        Income Growth
        """
        pass

    def test_equity_fundamental_latest_attributes(self) -> None:
        """Test case for equity_fundamental_latest_attributes

        Latest Attributes
        """
        pass

    def test_equity_fundamental_management(self) -> None:
        """Test case for equity_fundamental_management

        Management
        """
        pass

    def test_equity_fundamental_management_compensation(self) -> None:
        """Test case for equity_fundamental_management_compensation

        Management Compensation
        """
        pass

    def test_equity_fundamental_metrics(self) -> None:
        """Test case for equity_fundamental_metrics

        Metrics
        """
        pass

    def test_equity_fundamental_multiples(self) -> None:
        """Test case for equity_fundamental_multiples

        Multiples
        """
        pass

    def test_equity_fundamental_ratios(self) -> None:
        """Test case for equity_fundamental_ratios

        Ratios
        """
        pass

    def test_equity_fundamental_reported_financials(self) -> None:
        """Test case for equity_fundamental_reported_financials

        Reported Financials
        """
        pass

    def test_equity_fundamental_revenue_per_geography(self) -> None:
        """Test case for equity_fundamental_revenue_per_geography

        Revenue Per Geography
        """
        pass

    def test_equity_fundamental_revenue_per_segment(self) -> None:
        """Test case for equity_fundamental_revenue_per_segment

        Revenue Per Segment
        """
        pass

    def test_equity_fundamental_search_attributes(self) -> None:
        """Test case for equity_fundamental_search_attributes

        Search Attributes
        """
        pass

    def test_equity_fundamental_trailing_dividend_yield(self) -> None:
        """Test case for equity_fundamental_trailing_dividend_yield

        Trailing Dividend Yield
        """
        pass

    def test_equity_fundamental_transcript(self) -> None:
        """Test case for equity_fundamental_transcript

        Transcript
        """
        pass

    def test_equity_historical_market_cap(self) -> None:
        """Test case for equity_historical_market_cap

        Historical Market Cap
        """
        pass

    def test_equity_market_snapshots(self) -> None:
        """Test case for equity_market_snapshots

        Market Snapshots
        """
        pass

    def test_equity_ownership_form13f(self) -> None:
        """Test case for equity_ownership_form13f

        Form 13F
        """
        pass

    def test_equity_ownership_insider_trading(self) -> None:
        """Test case for equity_ownership_insider_trading

        Insider Trading
        """
        pass

    def test_equity_ownership_institutional(self) -> None:
        """Test case for equity_ownership_institutional

        Institutional
        """
        pass

    def test_equity_ownership_major_holders(self) -> None:
        """Test case for equity_ownership_major_holders

        Major Holders
        """
        pass

    def test_equity_ownership_share_statistics(self) -> None:
        """Test case for equity_ownership_share_statistics

        Share Statistics
        """
        pass

    def test_equity_price_historical(self) -> None:
        """Test case for equity_price_historical

        Historical
        """
        pass

    def test_equity_price_nbbo(self) -> None:
        """Test case for equity_price_nbbo

        Nbbo
        """
        pass

    def test_equity_price_performance(self) -> None:
        """Test case for equity_price_performance

        Performance
        """
        pass

    def test_equity_price_quote(self) -> None:
        """Test case for equity_price_quote

        Quote
        """
        pass

    def test_equity_profile(self) -> None:
        """Test case for equity_profile

        Profile
        """
        pass

    def test_equity_screener(self) -> None:
        """Test case for equity_screener

        Screener
        """
        pass

    def test_equity_search(self) -> None:
        """Test case for equity_search

        Search
        """
        pass

    def test_equity_shorts_fails_to_deliver(self) -> None:
        """Test case for equity_shorts_fails_to_deliver

        Fails To Deliver
        """
        pass


if __name__ == '__main__':
    unittest.main()
