# coding: utf-8

"""
    OpenBB Platform API

    Investment research for everyone, anywhere.

    The version of the OpenAPI document: 1
    Contact: hello@openbb.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openbb_client.models.fmp_balance_sheet_growth_data import FMPBalanceSheetGrowthData

class TestFMPBalanceSheetGrowthData(unittest.TestCase):
    """FMPBalanceSheetGrowthData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FMPBalanceSheetGrowthData:
        """Test FMPBalanceSheetGrowthData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FMPBalanceSheetGrowthData`
        """
        model = FMPBalanceSheetGrowthData()
        if include_optional:
            return FMPBalanceSheetGrowthData(
                period_ending = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                fiscal_period = '',
                fiscal_year = 56,
                symbol = '',
                growth_cash_and_cash_equivalents = 1.337,
                growth_short_term_investments = 1.337,
                growth_cash_and_short_term_investments = 1.337,
                growth_net_receivables = 1.337,
                growth_inventory = 1.337,
                growth_other_current_assets = 1.337,
                growth_total_current_assets = 1.337,
                growth_property_plant_equipment_net = 1.337,
                growth_goodwill = 1.337,
                growth_intangible_assets = 1.337,
                growth_goodwill_and_intangible_assets = 1.337,
                growth_long_term_investments = 1.337,
                growth_tax_assets = 1.337,
                growth_other_non_current_assets = 1.337,
                growth_total_non_current_assets = 1.337,
                growth_other_assets = 1.337,
                growth_total_assets = 1.337,
                growth_account_payables = 1.337,
                growth_short_term_debt = 1.337,
                growth_tax_payables = 1.337,
                growth_deferred_revenue = 1.337,
                growth_other_current_liabilities = 1.337,
                growth_total_current_liabilities = 1.337,
                growth_long_term_debt = 1.337,
                growth_deferred_revenue_non_current = 1.337,
                growth_deferrred_tax_liabilities_non_current = 1.337,
                growth_other_non_current_liabilities = 1.337,
                growth_total_non_current_liabilities = 1.337,
                growth_other_liabilities = 1.337,
                growth_total_liabilities = 1.337,
                growth_common_stock = 1.337,
                growth_retained_earnings = 1.337,
                growth_accumulated_other_comprehensive_income = 1.337,
                growth_other_total_shareholders_equity = 1.337,
                growth_total_shareholders_equity = 1.337,
                growth_total_liabilities_and_shareholders_equity = 1.337,
                growth_total_investments = 1.337,
                growth_total_debt = 1.337,
                growth_net_debt = 1.337
            )
        else:
            return FMPBalanceSheetGrowthData(
                period_ending = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                symbol = '',
                growth_property_plant_equipment_net = 1.337,
                growth_goodwill = 1.337,
                growth_intangible_assets = 1.337,
                growth_goodwill_and_intangible_assets = 1.337,
                growth_other_liabilities = 1.337,
                growth_total_liabilities = 1.337,
                growth_common_stock = 1.337,
                growth_retained_earnings = 1.337,
                growth_accumulated_other_comprehensive_income = 1.337,
        )
        """

    def testFMPBalanceSheetGrowthData(self):
        """Test FMPBalanceSheetGrowthData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
