# coding: utf-8

"""
    OpenBB Platform API

    Investment research for everyone, anywhere.

    The version of the OpenAPI document: 1
    Contact: hello@openbb.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openbb_client.models.fmp_price_target_data import FMPPriceTargetData

class TestFMPPriceTargetData(unittest.TestCase):
    """FMPPriceTargetData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FMPPriceTargetData:
        """Test FMPPriceTargetData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FMPPriceTargetData`
        """
        model = FMPPriceTargetData()
        if include_optional:
            return FMPPriceTargetData(
                published_date = None,
                published_time = '',
                symbol = '',
                exchange = '',
                company_name = '',
                analyst_name = '',
                analyst_firm = '',
                currency = '',
                price_target = 1.337,
                adj_price_target = 1.337,
                price_target_previous = 1.337,
                previous_adj_price_target = 1.337,
                price_when_posted = 1.337,
                rating_current = '',
                rating_previous = '',
                action = '',
                news_url = '',
                news_title = '',
                news_publisher = '',
                news_base_url = ''
            )
        else:
            return FMPPriceTargetData(
                published_date = None,
                symbol = '',
        )
        """

    def testFMPPriceTargetData(self):
        """Test FMPPriceTargetData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
