# coding: utf-8

"""
    OpenBB Platform API

    Investment research for everyone, anywhere.

    The version of the OpenAPI document: 1
    Contact: hello@openbb.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openbb_client.models.federal_reserve_central_bank_holdings_data import FederalReserveCentralBankHoldingsData

class TestFederalReserveCentralBankHoldingsData(unittest.TestCase):
    """FederalReserveCentralBankHoldingsData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FederalReserveCentralBankHoldingsData:
        """Test FederalReserveCentralBankHoldingsData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FederalReserveCentralBankHoldingsData`
        """
        model = FederalReserveCentralBankHoldingsData()
        if include_optional:
            return FederalReserveCentralBankHoldingsData(
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                security_type = '',
                description = '',
                is_aggreated = 'Y',
                cusip = '',
                issuer = '',
                maturity_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                term = '',
                face_value = 1.337,
                par_value = 1.337,
                coupon = 1.337,
                spread = 1.337,
                percent_outstanding = 1.337,
                bills = 1.337,
                frn = 1.337,
                notes_and_bonds = 1.337,
                tips = 1.337,
                mbs = 1.337,
                cmbs = 1.337,
                agencies = 1.337,
                total = 1.337,
                inflation_compensation = 1.337,
                change_prior_week = 1.337,
                change_prior_year = 1.337
            )
        else:
            return FederalReserveCentralBankHoldingsData(
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
        )
        """

    def testFederalReserveCentralBankHoldingsData(self):
        """Test FederalReserveCentralBankHoldingsData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
