# coding: utf-8

"""
    OpenBB Platform API

    Investment research for everyone, anywhere.

    The version of the OpenAPI document: 1
    Contact: hello@openbb.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openbb_client.models.benzinga_world_news_data import BenzingaWorldNewsData

class TestBenzingaWorldNewsData(unittest.TestCase):
    """BenzingaWorldNewsData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BenzingaWorldNewsData:
        """Test BenzingaWorldNewsData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BenzingaWorldNewsData`
        """
        model = BenzingaWorldNewsData()
        if include_optional:
            return BenzingaWorldNewsData(
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                title = '',
                images = [
                    {
                        'key' : ''
                        }
                    ],
                text = '',
                url = '',
                id = '',
                author = '',
                teaser = '',
                channels = '',
                stocks = '',
                tags = '',
                updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return BenzingaWorldNewsData(
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                title = '',
                id = '',
        )
        """

    def testBenzingaWorldNewsData(self):
        """Test BenzingaWorldNewsData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
