# coding: utf-8

"""
    OpenBB Platform API

    Investment research for everyone, anywhere.

    The version of the OpenAPI document: 1
    Contact: hello@openbb.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openbb_client.models.fmp_historical_employees_data import FMPHistoricalEmployeesData

class TestFMPHistoricalEmployeesData(unittest.TestCase):
    """FMPHistoricalEmployeesData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FMPHistoricalEmployeesData:
        """Test FMPHistoricalEmployeesData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FMPHistoricalEmployeesData`
        """
        model = FMPHistoricalEmployeesData()
        if include_optional:
            return FMPHistoricalEmployeesData(
                symbol = '',
                cik = 56,
                acceptance_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                period_of_report = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                company_name = '',
                form_type = '',
                filing_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                employee_count = 56,
                source = ''
            )
        else:
            return FMPHistoricalEmployeesData(
                symbol = '',
                cik = 56,
                acceptance_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                period_of_report = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                company_name = '',
                form_type = '',
                filing_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                employee_count = 56,
                source = '',
        )
        """

    def testFMPHistoricalEmployeesData(self):
        """Test FMPHistoricalEmployeesData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
