# coding: utf-8

"""
    OpenBB Platform API

    Investment research for everyone, anywhere.

    The version of the OpenAPI document: 1
    Contact: hello@openbb.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openbb_client.models.tiingo_company_news_data import TiingoCompanyNewsData

class TestTiingoCompanyNewsData(unittest.TestCase):
    """TiingoCompanyNewsData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TiingoCompanyNewsData:
        """Test TiingoCompanyNewsData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TiingoCompanyNewsData`
        """
        model = TiingoCompanyNewsData()
        if include_optional:
            return TiingoCompanyNewsData(
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                title = '',
                text = '',
                images = [
                    {
                        'key' : ''
                        }
                    ],
                url = '',
                symbols = '',
                tags = '',
                article_id = 56,
                source = '',
                crawl_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return TiingoCompanyNewsData(
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                title = '',
                url = '',
                article_id = 56,
                source = '',
                crawl_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testTiingoCompanyNewsData(self):
        """Test TiingoCompanyNewsData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
