# coding: utf-8

"""
    OpenBB Platform API

    Investment research for everyone, anywhere.

    The version of the OpenAPI document: 1
    Contact: hello@openbb.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openbb_client.models.fmp_currency_snapshots_data import FMPCurrencySnapshotsData

class TestFMPCurrencySnapshotsData(unittest.TestCase):
    """FMPCurrencySnapshotsData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FMPCurrencySnapshotsData:
        """Test FMPCurrencySnapshotsData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FMPCurrencySnapshotsData`
        """
        model = FMPCurrencySnapshotsData()
        if include_optional:
            return FMPCurrencySnapshotsData(
                base_currency = '',
                counter_currency = '',
                last_rate = 1.337,
                open = 1.337,
                high = 1.337,
                low = 1.337,
                close = 1.337,
                volume = 56,
                prev_close = 1.337,
                change = 1.337,
                change_percent = 1.337,
                ma_50 = 1.337,
                ma_200 = 1.337,
                year_high = 1.337,
                year_low = 1.337,
                last_rate_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return FMPCurrencySnapshotsData(
                base_currency = '',
                counter_currency = '',
                last_rate = 1.337,
        )
        """

    def testFMPCurrencySnapshotsData(self):
        """Test FMPCurrencySnapshotsData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
