# coding: utf-8

"""
    OpenBB Platform API

    Investment research for everyone, anywhere.

    The version of the OpenAPI document: 1
    Contact: hello@openbb.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openbb_client.models.y_finance_key_metrics_data import YFinanceKeyMetricsData

class TestYFinanceKeyMetricsData(unittest.TestCase):
    """YFinanceKeyMetricsData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> YFinanceKeyMetricsData:
        """Test YFinanceKeyMetricsData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `YFinanceKeyMetricsData`
        """
        model = YFinanceKeyMetricsData()
        if include_optional:
            return YFinanceKeyMetricsData(
                symbol = '',
                market_cap = 1.337,
                pe_ratio = 1.337,
                forward_pe = 1.337,
                peg_ratio = 1.337,
                peg_ratio_ttm = 1.337,
                eps_ttm = 1.337,
                eps_forward = 1.337,
                enterprise_to_ebitda = 1.337,
                earnings_growth = 1.337,
                earnings_growth_quarterly = 1.337,
                revenue_per_share = 1.337,
                revenue_growth = 1.337,
                enterprise_to_revenue = 1.337,
                cash_per_share = 1.337,
                quick_ratio = 1.337,
                current_ratio = 1.337,
                debt_to_equity = 1.337,
                gross_margin = 1.337,
                operating_margin = 1.337,
                ebitda_margin = 1.337,
                profit_margin = 1.337,
                return_on_assets = 1.337,
                return_on_equity = 1.337,
                dividend_yield = 1.337,
                dividend_yield_5y_avg = 1.337,
                payout_ratio = 1.337,
                book_value = 1.337,
                price_to_book = 1.337,
                enterprise_value = 56,
                overall_risk = 1.337,
                audit_risk = 1.337,
                board_risk = 1.337,
                compensation_risk = 1.337,
                shareholder_rights_risk = 1.337,
                beta = 1.337,
                price_return_1y = 1.337,
                currency = ''
            )
        else:
            return YFinanceKeyMetricsData(
        )
        """

    def testYFinanceKeyMetricsData(self):
        """Test YFinanceKeyMetricsData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
