# coding: utf-8

"""
    OpenBB Platform API

    Investment research for everyone, anywhere.

    The version of the OpenAPI document: 1
    Contact: hello@openbb.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openbb_client.models.fmp_discovery_filings_data import FMPDiscoveryFilingsData

class TestFMPDiscoveryFilingsData(unittest.TestCase):
    """FMPDiscoveryFilingsData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FMPDiscoveryFilingsData:
        """Test FMPDiscoveryFilingsData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FMPDiscoveryFilingsData`
        """
        model = FMPDiscoveryFilingsData()
        if include_optional:
            return FMPDiscoveryFilingsData(
                symbol = '',
                cik = '',
                title = '',
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                form_type = '',
                link = ''
            )
        else:
            return FMPDiscoveryFilingsData(
                symbol = '',
                cik = '',
                title = '',
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                form_type = '',
                link = '',
        )
        """

    def testFMPDiscoveryFilingsData(self):
        """Test FMPDiscoveryFilingsData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
