# coding: utf-8

"""
    OpenBB Platform API

    Investment research for everyone, anywhere.

    The version of the OpenAPI document: 1
    Contact: hello@openbb.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openbb_client.api.fixedincome_api import FixedincomeApi


class TestFixedincomeApi(unittest.TestCase):
    """FixedincomeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FixedincomeApi()

    def tearDown(self) -> None:
        pass

    def test_fixedincome_bond_indices(self) -> None:
        """Test case for fixedincome_bond_indices

        Bond Indices
        """
        pass

    def test_fixedincome_corporate_commercial_paper(self) -> None:
        """Test case for fixedincome_corporate_commercial_paper

        Commercial Paper
        """
        pass

    def test_fixedincome_corporate_hqm(self) -> None:
        """Test case for fixedincome_corporate_hqm

        Hqm
        """
        pass

    def test_fixedincome_corporate_ice_bofa(self) -> None:
        """Test case for fixedincome_corporate_ice_bofa

        This endpoint is deprecated; use `/fixedincome/bond_indices` instead. Deprecated in OpenBB Platform V4.2 to be removed in V4.5.
        """
        pass

    def test_fixedincome_corporate_moody(self) -> None:
        """Test case for fixedincome_corporate_moody

        This endpoint is deprecated; use `/fixedincome/bond_indices` instead. Set `category` to `us` and `index` to `seasoned_corporate`. Deprecated in OpenBB Platform V4.2 to be removed in V4.5.
        """
        pass

    def test_fixedincome_corporate_spot_rates(self) -> None:
        """Test case for fixedincome_corporate_spot_rates

        Spot Rates
        """
        pass

    def test_fixedincome_government_tips_yields(self) -> None:
        """Test case for fixedincome_government_tips_yields

        Tips Yields
        """
        pass

    def test_fixedincome_government_treasury_rates(self) -> None:
        """Test case for fixedincome_government_treasury_rates

        Treasury Rates
        """
        pass

    def test_fixedincome_government_us_yield_curve(self) -> None:
        """Test case for fixedincome_government_us_yield_curve

        This endpoint will be removed in a future version. Use, `/fixedincome/government/yield_curve`, instead. Deprecated in OpenBB Platform V4.2 to be removed in V4.4.
        """
        pass

    def test_fixedincome_government_yield_curve(self) -> None:
        """Test case for fixedincome_government_yield_curve

        Yield Curve
        """
        pass

    def test_fixedincome_mortgage_indices(self) -> None:
        """Test case for fixedincome_mortgage_indices

        Mortgage Indices
        """
        pass

    def test_fixedincome_rate_ameribor(self) -> None:
        """Test case for fixedincome_rate_ameribor

        Ameribor
        """
        pass

    def test_fixedincome_rate_dpcredit(self) -> None:
        """Test case for fixedincome_rate_dpcredit

        Dpcredit
        """
        pass

    def test_fixedincome_rate_ecb(self) -> None:
        """Test case for fixedincome_rate_ecb

        Ecb
        """
        pass

    def test_fixedincome_rate_effr(self) -> None:
        """Test case for fixedincome_rate_effr

        Effr
        """
        pass

    def test_fixedincome_rate_effr_forecast(self) -> None:
        """Test case for fixedincome_rate_effr_forecast

        Effr Forecast
        """
        pass

    def test_fixedincome_rate_estr(self) -> None:
        """Test case for fixedincome_rate_estr

        Estr
        """
        pass

    def test_fixedincome_rate_iorb(self) -> None:
        """Test case for fixedincome_rate_iorb

        Iorb
        """
        pass

    def test_fixedincome_rate_overnight_bank_funding(self) -> None:
        """Test case for fixedincome_rate_overnight_bank_funding

        Overnight Bank Funding
        """
        pass

    def test_fixedincome_rate_sofr(self) -> None:
        """Test case for fixedincome_rate_sofr

        Sofr
        """
        pass

    def test_fixedincome_rate_sonia(self) -> None:
        """Test case for fixedincome_rate_sonia

        Sonia
        """
        pass

    def test_fixedincome_sofr(self) -> None:
        """Test case for fixedincome_sofr

        This endpoint is deprecated; use `/fixedincome/rate/sofr` instead. Deprecated in OpenBB Platform V4.2 to be removed in V4.5.
        """
        pass

    def test_fixedincome_spreads_tcm(self) -> None:
        """Test case for fixedincome_spreads_tcm

        Tcm
        """
        pass

    def test_fixedincome_spreads_tcm_effr(self) -> None:
        """Test case for fixedincome_spreads_tcm_effr

        Tcm Effr
        """
        pass

    def test_fixedincome_spreads_treasury_effr(self) -> None:
        """Test case for fixedincome_spreads_treasury_effr

        Treasury Effr
        """
        pass


if __name__ == '__main__':
    unittest.main()
