# coding: utf-8

"""
    OpenBB Platform API

    Investment research for everyone, anywhere.

    The version of the OpenAPI document: 1
    Contact: hello@openbb.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openbb_client.models.fmp_calendar_dividend_data import FMPCalendarDividendData

class TestFMPCalendarDividendData(unittest.TestCase):
    """FMPCalendarDividendData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FMPCalendarDividendData:
        """Test FMPCalendarDividendData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FMPCalendarDividendData`
        """
        model = FMPCalendarDividendData()
        if include_optional:
            return FMPCalendarDividendData(
                ex_dividend_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                symbol = '',
                amount = 1.337,
                name = '',
                record_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                payment_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                declaration_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                adjusted_amount = 1.337,
                label = ''
            )
        else:
            return FMPCalendarDividendData(
                ex_dividend_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                symbol = '',
        )
        """

    def testFMPCalendarDividendData(self):
        """Test FMPCalendarDividendData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
