# coding: utf-8

"""
    OpenBB Platform API

    Investment research for everyone, anywhere.

    The version of the OpenAPI document: 1
    Contact: hello@openbb.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openbb_client.models.fmp_analyst_estimates_data import FMPAnalystEstimatesData

class TestFMPAnalystEstimatesData(unittest.TestCase):
    """FMPAnalystEstimatesData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FMPAnalystEstimatesData:
        """Test FMPAnalystEstimatesData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FMPAnalystEstimatesData`
        """
        model = FMPAnalystEstimatesData()
        if include_optional:
            return FMPAnalystEstimatesData(
                symbol = '',
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                estimated_revenue_low = 56,
                estimated_revenue_high = 56,
                estimated_revenue_avg = 56,
                estimated_sga_expense_low = 56,
                estimated_sga_expense_high = 56,
                estimated_sga_expense_avg = 56,
                estimated_ebitda_low = 56,
                estimated_ebitda_high = 56,
                estimated_ebitda_avg = 56,
                estimated_ebit_low = 56,
                estimated_ebit_high = 56,
                estimated_ebit_avg = 56,
                estimated_net_income_low = 56,
                estimated_net_income_high = 56,
                estimated_net_income_avg = 56,
                estimated_eps_avg = 1.337,
                estimated_eps_high = 1.337,
                estimated_eps_low = 1.337,
                number_analyst_estimated_revenue = 56,
                number_analysts_estimated_eps = 56
            )
        else:
            return FMPAnalystEstimatesData(
                symbol = '',
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
        )
        """

    def testFMPAnalystEstimatesData(self):
        """Test FMPAnalystEstimatesData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
