# coding: utf-8

"""
    OpenBB Platform API

    Investment research for everyone, anywhere.

    The version of the OpenAPI document: 1
    Contact: hello@openbb.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openbb_client.models.fmp_institutional_ownership_data import FMPInstitutionalOwnershipData

class TestFMPInstitutionalOwnershipData(unittest.TestCase):
    """FMPInstitutionalOwnershipData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FMPInstitutionalOwnershipData:
        """Test FMPInstitutionalOwnershipData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FMPInstitutionalOwnershipData`
        """
        model = FMPInstitutionalOwnershipData()
        if include_optional:
            return FMPInstitutionalOwnershipData(
                symbol = '',
                cik = '',
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                investors_holding = 56,
                last_investors_holding = 56,
                investors_holding_change = 56,
                number_of_13f_shares = 56,
                last_number_of_13f_shares = 56,
                number_of_13f_shares_change = 56,
                total_invested = 1.337,
                last_total_invested = 1.337,
                total_invested_change = 1.337,
                ownership_percent = 1.337,
                last_ownership_percent = 1.337,
                ownership_percent_change = 1.337,
                new_positions = 56,
                last_new_positions = 56,
                new_positions_change = 56,
                increased_positions = 56,
                last_increased_positions = 56,
                increased_positions_change = 56,
                closed_positions = 56,
                last_closed_positions = 56,
                closed_positions_change = 56,
                reduced_positions = 56,
                last_reduced_positions = 56,
                reduced_positions_change = 56,
                total_calls = 56,
                last_total_calls = 56,
                total_calls_change = 56,
                total_puts = 56,
                last_total_puts = 56,
                total_puts_change = 56,
                put_call_ratio = 1.337,
                last_put_call_ratio = 1.337,
                put_call_ratio_change = 1.337
            )
        else:
            return FMPInstitutionalOwnershipData(
                symbol = '',
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                investors_holding = 56,
                last_investors_holding = 56,
                investors_holding_change = 56,
                total_invested = 1.337,
                last_total_invested = 1.337,
                total_invested_change = 1.337,
                ownership_percent = 1.337,
                last_ownership_percent = 1.337,
                ownership_percent_change = 1.337,
                new_positions = 56,
                last_new_positions = 56,
                new_positions_change = 56,
                increased_positions = 56,
                last_increased_positions = 56,
                increased_positions_change = 56,
                closed_positions = 56,
                last_closed_positions = 56,
                closed_positions_change = 56,
                reduced_positions = 56,
                last_reduced_positions = 56,
                reduced_positions_change = 56,
                total_calls = 56,
                last_total_calls = 56,
                total_calls_change = 56,
                total_puts = 56,
                last_total_puts = 56,
                total_puts_change = 56,
                put_call_ratio = 1.337,
                last_put_call_ratio = 1.337,
                put_call_ratio_change = 1.337,
        )
        """

    def testFMPInstitutionalOwnershipData(self):
        """Test FMPInstitutionalOwnershipData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
