# coding: utf-8

"""
    OpenBB Platform API

    Investment research for everyone, anywhere.

    The version of the OpenAPI document: 1
    Contact: hello@openbb.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openbb_client.models.sec_sic_search_data import SecSicSearchData

class TestSecSicSearchData(unittest.TestCase):
    """SecSicSearchData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SecSicSearchData:
        """Test SecSicSearchData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SecSicSearchData`
        """
        model = SecSicSearchData()
        if include_optional:
            return SecSicSearchData(
                sic = 56,
                industry = '',
                office = ''
            )
        else:
            return SecSicSearchData(
                sic = 56,
                industry = '',
                office = '',
        )
        """

    def testSecSicSearchData(self):
        """Test SecSicSearchData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
