# coding: utf-8

"""
    OpenBB Platform API

    Investment research for everyone, anywhere.

    The version of the OpenAPI document: 1
    Contact: hello@openbb.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openbb_client.models.intrinio_world_news_data import IntrinioWorldNewsData

class TestIntrinioWorldNewsData(unittest.TestCase):
    """IntrinioWorldNewsData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IntrinioWorldNewsData:
        """Test IntrinioWorldNewsData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IntrinioWorldNewsData`
        """
        model = IntrinioWorldNewsData()
        if include_optional:
            return IntrinioWorldNewsData(
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                title = '',
                images = [
                    {
                        'key' : ''
                        }
                    ],
                text = '',
                url = '',
                source = '',
                summary = '',
                topics = '',
                word_count = 56,
                business_relevance = 1.337,
                sentiment = '',
                sentiment_confidence = 1.337,
                language = '',
                spam = True,
                copyright = '',
                id = '',
                company = { },
                security = { }
            )
        else:
            return IntrinioWorldNewsData(
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                title = '',
                id = '',
        )
        """

    def testIntrinioWorldNewsData(self):
        """Test IntrinioWorldNewsData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
