# coding: utf-8

"""
    OpenBB Platform API

    Investment research for everyone, anywhere.

    The version of the OpenAPI document: 1
    Contact: hello@openbb.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openbb_client.models.is_inline_xbrl import IsInlineXbrl

class TestIsInlineXbrl(unittest.TestCase):
    """IsInlineXbrl unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IsInlineXbrl:
        """Test IsInlineXbrl
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IsInlineXbrl`
        """
        model = IsInlineXbrl()
        if include_optional:
            return IsInlineXbrl(
            )
        else:
            return IsInlineXbrl(
        )
        """

    def testIsInlineXbrl(self):
        """Test IsInlineXbrl"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
