# coding: utf-8

"""
    OpenBB Platform API

    Investment research for everyone, anywhere.

    The version of the OpenAPI document: 1
    Contact: hello@openbb.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openbb_client.models.fmp_etf_info_data import FMPEtfInfoData

class TestFMPEtfInfoData(unittest.TestCase):
    """FMPEtfInfoData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FMPEtfInfoData:
        """Test FMPEtfInfoData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FMPEtfInfoData`
        """
        model = FMPEtfInfoData()
        if include_optional:
            return FMPEtfInfoData(
                symbol = '',
                name = '',
                description = '',
                inception_date = '',
                issuer = '',
                cusip = '',
                isin = '',
                domicile = '',
                asset_class = '',
                aum = 1.337,
                nav = 1.337,
                nav_currency = '',
                expense_ratio = 1.337,
                holdings_count = 56,
                avg_volume = 1.337,
                website = ''
            )
        else:
            return FMPEtfInfoData(
                symbol = '',
                name = '',
                inception_date = '',
        )
        """

    def testFMPEtfInfoData(self):
        """Test FMPEtfInfoData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
