# coding: utf-8

"""
    OpenBB Platform API

    Investment research for everyone, anywhere.

    The version of the OpenAPI document: 1
    Contact: hello@openbb.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openbb_client.models.sec_company_filings_data import SecCompanyFilingsData

class TestSecCompanyFilingsData(unittest.TestCase):
    """SecCompanyFilingsData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SecCompanyFilingsData:
        """Test SecCompanyFilingsData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SecCompanyFilingsData`
        """
        model = SecCompanyFilingsData()
        if include_optional:
            return SecCompanyFilingsData(
                filing_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                accepted_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                symbol = '',
                cik = '',
                report_type = '',
                filing_url = '',
                report_url = '',
                report_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                act = None,
                items = None,
                primary_doc_description = '',
                primary_doc = '',
                accession_number = None,
                file_number = None,
                film_number = None,
                is_inline_xbrl = None,
                is_xbrl = None,
                size = None,
                complete_submission_url = '',
                filing_detail_url = ''
            )
        else:
            return SecCompanyFilingsData(
                filing_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                report_url = '',
        )
        """

    def testSecCompanyFilingsData(self):
        """Test SecCompanyFilingsData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
