# coding: utf-8

"""
    OpenBB Platform API

    Investment research for everyone, anywhere.

    The version of the OpenAPI document: 1
    Contact: hello@openbb.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openbb_client.models.y_finance_index_historical_data import YFinanceIndexHistoricalData

class TestYFinanceIndexHistoricalData(unittest.TestCase):
    """YFinanceIndexHistoricalData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> YFinanceIndexHistoricalData:
        """Test YFinanceIndexHistoricalData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `YFinanceIndexHistoricalData`
        """
        model = YFinanceIndexHistoricalData()
        if include_optional:
            return YFinanceIndexHistoricalData(
                var_date = None,
                open = 1.337,
                high = 1.337,
                low = 1.337,
                close = 1.337,
                volume = 56
            )
        else:
            return YFinanceIndexHistoricalData(
                var_date = None,
        )
        """

    def testYFinanceIndexHistoricalData(self):
        """Test YFinanceIndexHistoricalData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
